In [32]:
import numpy as np
import pandas as pd

In [33]:
# Simulé les données

np.random.seed(42)
num_sample = 10

In [34]:
age = np.random.randint(18, 90, num_sample)
age

array([69, 32, 89, 78, 38, 41, 20, 39, 70, 19])

In [35]:
income = np.random.randint(20000, 100000, num_sample)
income


array([79735, 82955, 84925, 87969, 25311, 73707, 48693, 91932, 45658,
       38431])

In [36]:
loan_amount = income = np.random.randint(50000, 100000, num_sample)

In [37]:
num_acounts = np.random.randint(1, 10, num_sample)

In [38]:
# création des caractéristique d'entrée
x = np.column_stack((age, income, loan_amount, num_acounts))
x

array([[   69, 52747, 52747,     7],
       [   32, 50189, 50189,     5],
       [   89, 69118, 69118,     9],
       [   78, 85773, 85773,     7],
       [   38, 51899, 51899,     2],
       [   41, 51267, 51267,     4],
       [   20, 81551, 81551,     9],
       [   39, 61394, 61394,     2],
       [   70, 53556, 53556,     9],
       [   19, 53890, 53890,     5]])

In [39]:
x = np.column_stack((age, income, loan_amount, num_acounts)).T
x

array([[   69,    32,    89,    78,    38,    41,    20,    39,    70,
           19],
       [52747, 50189, 69118, 85773, 51899, 51267, 81551, 61394, 53556,
        53890],
       [52747, 50189, 69118, 85773, 51899, 51267, 81551, 61394, 53556,
        53890],
       [    7,     5,     9,     7,     2,     4,     9,     2,     9,
            5]])

In [40]:
# Fonction d'activation Relu
def relu(x):
  return np.maximum(0,x)

# fonction d'activation sigmoide
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [41]:
# Nombre de neurones
hidden_size = 5
np.random.seed(42)
w1 = np.random.rand(hidden_size, x.shape[0])
w1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [42]:
b1 = np.random.rand(hidden_size,1)
b1

array([[0.61185289],
       [0.13949386],
       [0.29214465],
       [0.36636184],
       [0.45606998]])

In [43]:
output_size  = 1
w2 = np.random.rand(output_size, hidden_size)
b2 = np.random.rand(output_size,1)

In [44]:
# forward pass
z1 = np.dot(w1,x) + b1
z1

array([[ 88788.45769941,  84469.0346991 , 116344.76255039,
        144364.95116624,  87346.91706882,  86285.76639327,
        137240.03093233, 103324.6064258 ,  90151.34052931,
         90691.86890422],
       [ 11308.94726828,  10753.83036335,  14818.47310061,
         18380.49584014,  11118.24155333,  10985.14458181,
         17469.34123585,  13151.0694401 ,  11484.02484841,
         11544.10528942],
       [ 38483.03303105,  36594.9471655 ,  50425.84007821,
         62553.07152906,  37841.64771929,  37384.87961447,
         59443.75651972,  44760.84773382,  39075.05753709,
         39283.89249416],
       [ 20850.06135185,  19810.62245389,  27319.93713274,
         33875.21617186,  20489.08746939,  20242.83990911,
         32163.14057088,  24232.50783155,  21170.13934252,
         21258.60195181],
       [ 50486.61878635,  48027.53705528,  66155.44553193,
         82085.3790633 ,  49664.44830129,  49061.30816972,
         78029.12194843,  58748.63281388,  51261.47696015,
         51

In [45]:
a1 = relu(z1)
a1

array([[ 88788.45769941,  84469.0346991 , 116344.76255039,
        144364.95116624,  87346.91706882,  86285.76639327,
        137240.03093233, 103324.6064258 ,  90151.34052931,
         90691.86890422],
       [ 11308.94726828,  10753.83036335,  14818.47310061,
         18380.49584014,  11118.24155333,  10985.14458181,
         17469.34123585,  13151.0694401 ,  11484.02484841,
         11544.10528942],
       [ 38483.03303105,  36594.9471655 ,  50425.84007821,
         62553.07152906,  37841.64771929,  37384.87961447,
         59443.75651972,  44760.84773382,  39075.05753709,
         39283.89249416],
       [ 20850.06135185,  19810.62245389,  27319.93713274,
         33875.21617186,  20489.08746939,  20242.83990911,
         32163.14057088,  24232.50783155,  21170.13934252,
         21258.60195181],
       [ 50486.61878635,  48027.53705528,  66155.44553193,
         82085.3790633 ,  49664.44830129,  49061.30816972,
         78029.12194843,  58748.63281388,  51261.47696015,
         51

In [46]:
z2 = np.dot(w2,a1) + b2
z2

array([[106459.57571802, 101256.30343647, 139498.95898383,
        173070.61491873, 104707.77497522, 103439.22635749,
        164492.77493447, 123856.68682305, 108094.68769305,
        108704.95856706]])

In [47]:
a2 = sigmoid(z2)
a2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])